services:
  - type: static
    name: restro-hub
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://hotel-vpuj.onrender.com
    routes:
      - path: /*
        destination: /index.html
        status: 200
